2024-07-29 10:16:22,327 INFO    MainThread:1200216 [wandb_setup.py:_flush():76] Current SDK version is 0.17.5
2024-07-29 10:16:22,328 INFO    MainThread:1200216 [wandb_setup.py:_flush():76] Configure stats pid to 1200216
2024-07-29 10:16:22,328 INFO    MainThread:1200216 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2024-07-29 10:16:22,328 INFO    MainThread:1200216 [wandb_setup.py:_flush():76] Loading settings from /root/seg_framework/MS-Mamba/run_scripts/wandb/settings
2024-07-29 10:16:22,328 INFO    MainThread:1200216 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-29 10:16:22,328 INFO    MainThread:1200216 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-29 10:16:22,328 WARNING MainThread:1200216 [wandb_setup.py:_flush():76] Could not find program at -m train_mslesseg
2024-07-29 10:16:22,328 INFO    MainThread:1200216 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '-m train_mslesseg'}
2024-07-29 10:16:22,328 INFO    MainThread:1200216 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-29 10:16:22,328 INFO    MainThread:1200216 [wandb_init.py:_log_setup():529] Logging user logs to /root/seg_framework/MS-Mamba/run_scripts/wandb/run-20240729_101622-s6tb78tl/logs/debug.log
2024-07-29 10:16:22,328 INFO    MainThread:1200216 [wandb_init.py:_log_setup():530] Logging internal logs to /root/seg_framework/MS-Mamba/run_scripts/wandb/run-20240729_101622-s6tb78tl/logs/debug-internal.log
2024-07-29 10:16:22,328 INFO    MainThread:1200216 [wandb_init.py:init():569] calling init triggers
2024-07-29 10:16:22,328 INFO    MainThread:1200216 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {'accum_iter': 1, 'model': 'SegFormer3D', 'in_channels': 1, 'lr': None, 'blr': 0.001, 'min_lr': 0, 'dist_on_itp': False, 'warmup_epochs': 20, 'device': 'cuda:0', 'seed': 42, 'layer_decay': 0.75, 'clip_grad': None, 'num_workers': 8, 'pin_mem': True, 'resume': '', 'world_size': 1, 'embed_dim': 1, 'local_rank': -1, 'dist_url': 'env://', 'nb_classes': 2, 'data_dir': '/root/MSLesSeg24/data', 'datalist': None, 'modalities': 'T1,T2,FLAIR,T1ce', 'preprocess': False}
2024-07-29 10:16:22,328 INFO    MainThread:1200216 [wandb_init.py:init():619] starting backend
2024-07-29 10:16:22,328 INFO    MainThread:1200216 [wandb_init.py:init():623] setting up manager
2024-07-29 10:16:22,330 INFO    MainThread:1200216 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-07-29 10:16:22,330 INFO    MainThread:1200216 [wandb_init.py:init():631] backend started and connected
2024-07-29 10:16:22,334 INFO    MainThread:1200216 [wandb_init.py:init():720] updated telemetry
2024-07-29 10:16:22,337 INFO    MainThread:1200216 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-07-29 10:16:22,640 ERROR   MainThread:1200216 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-07-29 10:16:22,640 ERROR   MainThread:1200216 [wandb_init.py:init():1191] error in wandb.init()
Traceback (most recent call last):
  File "/root/anaconda3/envs/vivim/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    return wi.init()
  File "/root/anaconda3/envs/vivim/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-07-29 10:16:23,703 WARNING MsgRouterThr:1200216 [router.py:message_loop():77] message_loop has been closed
